AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyRoleName:
    Type: String
    Default: 'k8slabRW-readonly-role'
Resources:
  ReadOnlyRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::578124968738:root'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/job-function/ViewOnlyAccess'
      Policies:
        - PolicyName: sts-assume-role-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource: !Sub 'arn:aws:iam::*:role/${MyRoleName}'                  
                Action: 'sts:AssumeRole'
      RoleName: !Ref MyRoleName  
